### ISSUE TITLE
How to apply texture or clothes to gui3d.app.selectedHuman object?

### ISSUE THREAD

**Issue by Hlings** [makehumancommunity/makehuman#147] opened 2020-12-22 10:03 UTC
I want to use scripting window of the makehuman software to build my own script for making human.  After creating a gui3d.app.selectedHuman object, I can't find api about applying texture or clothes, etc. I have read mhapi docs. Is there any other docs about other api for making human or I have to read source code for using?
Thanks.!

**Comment by Aranuvir** [comment] 2020-12-22 22:37
That's something to be asked in the forums.

You might want to take a look at the library scripts in the plugins folder to find out how things work. 

Not a bug, closing...

**Closed by Aranuvir** 2020-12-22 22:37 UTC
