### ISSUE TITLE
Model with pose glitches while moving the height slider

### ISSUE THREAD

**Issue by unit73e** [makehumancommunity/makehuman#30] opened 2019-01-13 18:51 UTC
The model glitches while moving the height slider if it has a pose other than none.

A model with Standing01 pose is rendered correctly:
![image](https://user-images.githubusercontent.com/11358308/51089336-72660300-1763-11e9-9b3f-e54583a9b691.png)

But glitches while moving the height slider:
![image](https://user-images.githubusercontent.com/11358308/51089363-c7a21480-1763-11e9-99a4-ddcf8087bbe4.png)

Fortunately it will be rendered properly when the slider is released:
![image](https://user-images.githubusercontent.com/11358308/51089378-fa4c0d00-1763-11e9-9f63-6535cc3fdc4f.png)

**Comment by Aranuvir** [comment] 2019-01-13 20:36
I can confirm the issue. We will have to investigate.

**Comment by rwbaer** [comment] 2019-01-14 01:41
This behavior is by design.  It used to be that moving sliders only caused a single update on release.  A change was introduced to allow updating DURING slider movement, but the message cue was spammed by so much updating that the program bogged.  Currently the behavior is to reflect partially track slider the moving slider with the time consuming update left for mouse up.  Perhaps there are alternate solutions, but that is the history.

**Comment by Aranuvir** [comment] 2019-01-14 21:16
Some further reasons against an auto toggle are here: http://issues.makehumancommunity.org/issues/97
BTW, MakeHuman has an easily accessible toggle button for the poses. 
Currently I'll give it a wontfix.

**Closed by Aranuvir** 2019-01-14 21:16 UTC
Labels: wontfix
