### ISSUE TITLE
Port fbx exporter to Python3, rebase the exporter on the official fbx python sdk.

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/makehuman#3] opened 2017-07-09 10:33 UTC
I had tried to port the fbx exporter to Python3 which quickly drove me nuts...

IIRC great parts of the code are based on the blender fbx exporter. While porting the exporter to python3 we should check, if the code is still up to date and consider if we should rebase it on the official fbx python sdk. The sdk seems to be redistributable. Does it really make things worse distributing a closed library on an open source project, while sticking on a more or less closed export format?

**Comment by joepal1976** [comment] 2017-07-10 13:19
The problem with the fbx sdk is not only that it is very troublesome concerning its license. The greater show-stopper is that it's a c++ library with a python wrapper. Since all we get is a binary blob we can only hope it will work on all the platforms users run MH on. For windows there are six different versions to keep track of. 

On top of that, the download for linux is 70mb for the SDK and another 30mb for the python wrapper. 

For the protocol: the full license of the SDK is here https://damassets.autodesk.net/content/dam/autodesk/www/Company/docs/pdf/legal-notices-&-trademarks/Autodesk_FBX_SDK_2014_LSA_-_English.pdf

**Comment by rwbaer** [comment] 2017-07-10 21:35
What would be useful to document on the issue tracker (http://bugtracker.makehumancommunity.org/projects/py3port/activity )
is exactly in what was FBX export fails in this branch.  I haven't spent much time testing, but if you have discovered some reproducible issues, it can help focus additional testing and development of specific solutions.

I hope we can also start to document other failures (like the  Linux mesa driver failure) on this bug tracker.  We are at a stage where there may be platform differences in what does or doesn't work so specifying environment for these tests may also be important - build/branch  (commit), OS, etc..

**Comment by joepal1976** [comment] 2018-02-12 11:05
There is now a feature branch for porting FBX. See https://github.com/makehumancommunity/makehuman/tree/_bugfix_port_fbx

**Comment by joepal1976** [comment] 2018-11-07 08:18
While there are still issues, there is a somewhat working port of FBX now.

**Comment by joepal1976** [comment] 2018-12-11 13:57
While there are still issues, the porting and updating as such is now finished. Closing this in favor of more detailed FBX bug reports.

**Closed by joepal1976** 2018-12-11 13:57 UTC
Labels: bug, c: normal
