### ISSUE TITLE
MakeHuman doesn't work on Mac with BigSur

### ISSUE THREAD

**Issue by Aiglentine** [makehumancommunity/makehuman#141] opened 2020-11-17 08:16 UTC
Hello,

MakeHuman doesn't work on Mac with BigSur.
Can you help me work around this problem?
Thank you so much.

**Comment by Aranuvir** [comment] 2020-11-17 20:21
The problem is no one uses apple products, so we cannot investigate on those specific issues and bug reports kind of "it doesn't work"  are slightly insufficient for further help.
As far as I know apple has dropped OpenGL support, so I assume MakeHuman will not run on apple products anyway. Perhaps you can find some apple users in our forum who can give you further advice.

**Comment by Aiglentine** [comment] 2020-11-18 09:24
Thank you for your reply.
In fact, makeHuman (which is a fabulous program) worked great on OSX Catalina, and since the last update this week (OSX big Sur), the program won't start anymore.
This is obviously a Mac problem, hope someone can find a solution.
Thank you.

**Comment by Radzievskyi** [comment] 2020-12-03 09:40
I find solution. Make Human work on macOS Big Sur without problem if fix one bug in python OpenGL Library.

I use Python 3.9, so for me fix look like this:

1. Go to: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/OpenGL/platform/
2. Open: **ctypesloader.py**
3. Replace line:
          **fullName = util.find_library(name)**
To:
          **fullName = '/System/Library/Frameworks/OpenGL.framework/OpenGL'**

**Comment by Aiglentine** [comment] 2020-12-03 17:23
Many thanks for your quick reply with all this informations.
However, it remains one problem. I don't have the folder "openGL" in "fullName = '/System/Library/Frameworks/OpenGL.framework/OpenGL'".
Do I need to install openGL extension or other ?

Thanks for your help.

**Comment by Radzievskyi** [comment] 2020-12-03 18:02
As I read, no need any additional installs or creating folder. This changing should be enough for Make Human start work.

**Comment by Aiglentine** [comment] 2020-12-05 10:02
Thank you for your reply.
But it still doesn't start, I install Python 3.9, with all dependencies but no issue. When i try to go to /System/Library/Frameworks/OpenGL.framework/OpenGL, the link is inreachable because there is no folder .../OpenGL in OpenGL.framework/ .. i search on google and some people have the same problem... I don't know how to get this files in this folder.

**Comment by Radzievskyi** [comment] 2020-12-05 11:55
Did you replace line:
fullName = util.find_library(name)
To:
fullName = '/System/Library/Frameworks/OpenGL.framework/OpenGL'
?

And try launch Make Human with this command from terminal:
python3 makehuman.py

**Comment by Aiglentine** [comment] 2020-12-05 15:56
it's ok now, after install the version 1.1.0 and change again the fullname ! Thank you very much for your help 
i Keep those informations for next time !
Bye !

**Comment by david-salcedo** [comment] 2021-03-26 10:22
hello there, i have the same problem but i can't understand the solution. In my case the "OpenGL" folder not exist. So what can i do?

**Comment by Aiglentine** [comment] 2021-03-28 18:13
Hello,

You can download the new version of MH today. 

If not, you can download the old version 1.1, it works. 

Envoyé de mon iPhone

**Comment by threos** [comment] 2021-06-15 14:13
Hi,

You can download modified OpenGL wrapper from http://download.tuxfamily.org/makehuman/build/macos-opengl-wrapper.zip. Extract OpenGL folder to repository root, then program should work.

Also, a Mac build is available at http://makehumancommunity.org

**Comment by Aiglentine** [comment] 2021-06-19 07:15
HI, 

Thank you very much for your work !

**Comment by Aranuvir** [comment] 2021-06-20 16:17
I think this was resolved. Closing..

**Closed by Aranuvir** 2021-06-20 16:17 UTC
Labels: c: low
