### ISSUE TITLE
freeze after content download from community

### ISSUE THREAD

**Issue by Atalantia** [makehumancommunity/makehuman#176] opened 2021-09-24 08:55 UTC
macos 10.13
Many times the app freezes completely after the download has finished. Also the (unnesesary) pop-up "Download complete" or so doesn't appear by this event. MH needs to bee hard shut down and restarted.

**Comment by Aranuvir** [comment] 2021-10-07 20:53
Closing. It is a duplicate of #157.

**Closed by Aranuvir** 2021-10-07 20:53 UTC
Labels: duplicate
