### ISSUE TITLE
Litsphere shader texture

### ISSUE THREAD

**Issue by rwbaer** [makehumancommunity/makehuman#100] opened 2020-06-13 11:44 UTC
version 1.2.0 Beta1 (HEAD:748a570b) Windows 10

Asset node id 970 is star_teeth_tri with litsphere (Marco105).  At some time in the past I downloaded it and my recollection is that it did no produce errors. Now it produces: Cannot get texture for file path lit_teeth_gray.PNG, no such file.  Checking the mhmat file this seems the line of interest:
shaderParam litsphereTexture lit_teeth_gray.PNG

Because this is an unusual use and I don't remember the error before, I want to be sure it is not the result of some rearrangement to the code or accidental loss of an asset that was previously present.

**Comment by Aranuvir** [comment] 2020-06-21 18:27
You are sure to have the litsphere? And check the spelling... 

Otherwise get the litsphere from here: http://www.makehumancommunity.org/clothes/star_teeth_tri_with_litsphere.html 

Quote from Marco:
>My illustration is the litsphere you need.

Probably not a bug, but leaving it open for further investigations.

**Comment by Aranuvir** [comment] 2020-06-24 21:47
Hello Rob, any updates here? Can we close the issue?

**Comment by Aranuvir** [comment] 2020-06-26 19:32
No further input here, consider this not a bug.

**Closed by Aranuvir** 2020-06-26 19:32 UTC
Labels: invalid
