### ISSUE TITLE
FBX export don't work

### ISSUE THREAD

**Issue by thankjura** [makehumancommunity/makehuman#7] opened 2017-12-07 11:50 UTC
AranuvirQt5 branch. Can't export to fbx.

> Exception during event onFileSelected
> Traceback (most recent call last):
>   File "./core/events3d.py", line 211, in callEvent
>     method(event)
>   File "./apps/gui/guiexport.py", line 112, in onFileSelected
>     exporter.export(gui3d.app.selectedHuman, filename)
>   File "plugins/9_export_fbx/__init__.py", line 105, in export
>     mh2fbx.exportFbx(filename("fbx"), cfg)
>   File "plugins/9_export_fbx/mh2fbx.py", line 155, in exportFbx
>     fbx_mesh.writeObjectProps(fp, meshes, config)
>   File "plugins/9_export_fbx/fbx_mesh.py", line 89, in writeObjectProps
>     writeGeometryProp(fp, mesh, config)
>   File "plugins/9_export_fbx/fbx_mesh.py", line 107, in writeGeometryProp
>     fbx_binary.fbx_data_mesh_element(elem, key, id, properties, coord, mesh.fvert, mesh.vnorm, mesh.texco, mesh.fuvs)
>   File "plugins/9_export_fbx/fbx_binary.py", line 258, in fbx_data_mesh_element
>     geom.add_string(fbx_name_class(key.encode()))
>   File "plugins/9_export_fbx/fbx_utils_bin.py", line 578, in fbx_name_class
>     cls,name = name.split('::')
> TypeError: a bytes-like object is required, not 'str'

**Comment by joepal1976** [comment] 2017-12-07 12:24
Yes, this is known, and one of the major problems with the py3 conversion: The binary-centric export for FBX did not gracefully survive the conversion from py2. 

Atm, the lack of functional FBX is one of the major showstoppers in the py3 branch.

**Comment by Aranuvir** [comment] 2017-12-07 16:48
This is in most parts issue #3.

**Comment by rwbaer** [comment] 2017-12-12 12:26
So this is against the Aranuvir branch.  Does it reproduce on master as well or is this a side-effect of porting towards the SDK?   It looks like it might be a simple string versus byte thing as the result of python 3's new defaults although I haven't checked yet.

**Comment by Aranuvir** [comment] 2017-12-12 13:22
It will not work on any branch I currently know, simply because it wasn't ported to Python3 yet. I once tried to touch the code, which went soon completely messy, so I decided to revert al my porting attempts. Remembering those multiple bug reports on the old bug tracker,  I consider this thing unusable, anyway, and for me the exporter is negligible. The only reason to keep it in the project is because it is the most common format in the closed source world. (Though I personally prefer the MHX2 -> Blender -> FBX pipeline).

**Comment by joepal1976** [comment] 2018-02-12 11:06
Closing this in favor of #3. 

There is a now a feature branch with FBX fixes at https://github.com/makehumancommunity/makehuman/tree/_bugfix_port_fbx

**Closed by joepal1976** 2018-02-12 11:06 UTC
Labels: duplicate, help wanted
