### ISSUE TITLE
Settings not loaded properly

### ISSUE THREAD

**Issue by alfredorusso-github** [makehumancommunity/makehuman#223] opened 2023-03-31 16:22 UTC
There is a bug that prevents changing the settings in MakeHuman. The bug is related to an error that occurs when MakeHuman is started, which prevents the settings from being correctly loaded. As a result, the default settings are created and utilized every time, and some plugins cannot be activated.

This issue needs to be addressed in order to enable changing the settings and activating all plugins.

The error is caused by the `parseINI` method in the `/makehuman/lib/inifile.py` file. In this method, `json.loads(s, encoding='utf-8')` is used. However, since Python 3.9, the `encoding` keyword argument is deprecated and it is no longer necessary to specify the encoding type. The method itself calls `detect_encoding()`, which is able to recognize the input encoding.

The solution for the bug that worked for me is the following:
[inifile.zip](https://github.com/makehumancommunity/makehuman/files/11123977/inifile.zip)

**Comment by Aranuvir** [comment] 2024-06-25 19:24
Strangely MakeHuman does not show an error on my system. Though I can reproduce the issue in a quick test in Python. Evaluating your explanation and checking the documentation this seems to be quite reasonable. Should be fixed soon...

**Comment by Aranuvir** [comment] 2024-06-26 07:29
Should be fixed with commit 4f37318b1f052cb54fd88a129d65f044986ed751.

Closing. Could be reopened in case there are further issues.

**Closed by Aranuvir** 2024-06-26 07:29 UTC
Labels: bug, c: high

**Comment by black-punkduck** [comment] 2024-06-26 18:56
should be okay. 

settings.ini usually can have two topics with none ASCII codes:

pathnames with special characters ... what about German "öffentlicher Ordner" ;)

Awful tags. And there we already have one. Makehuman + the TM symbol. But afaik it works with JSON.

The discussion what JSON can do or can't do in stackexchange is endless. It is usually more a problem around HTML or Java-Script or when APIs will classically deliver nothing (from daily business) but an error-code ... 

the other .ini files are just tables and not JSON.

**Comment by Aranuvir** [comment] 2024-06-26 21:26
Feel free to change the tags ;)

Btw, I had fixed that issue 4 years ago. And I cannot tell from the history how the code was reverted.  Confusing.
