### ISSUE TITLE
1.2.0 beta 2 archive corrupt

### ISSUE THREAD

**Issue by gebeleizis** [makehumancommunity/makehuman#124] opened 2020-09-04 09:05 UTC
I've tried to run it, but could not extract the files. Can you, please, check the archive integrity? Thank you!

**Comment by Aranuvir** [comment] 2020-09-05 22:48
Cannot reproduce the problem, at least I was able to unzip the package on Linux system, though I didn't test if the files are executable. The only thing I can say download speed was terribly slow and it took >60 times longer than it was supposed to take based on my internet speed. It might be possible your file got corrupted due to an incomplete or defective transmission. Maybe you should consider to use a download manager.
And we definitely should tidy up our tuxfamily repo, in the hope this will reduce server load and increase overall speed for downloads.

Closing this issue. For further assistance on that topic I'd recommend our forum. Could be reopened if we get further important information...

**Closed by Aranuvir** 2020-09-05 22:48 UTC
Labels: invalid
