### ISSUE TITLE
Download Plugins on Mac?

### ISSUE THREAD

**Issue by nisfinx** [makehumancommunity/makehuman#11] opened 2018-03-15 18:18 UTC
I tried to follow tutorials on YouTube on how to download plugins for MakeHuman but they are on Windows and when I copy what they do, there isn't an option to download the file. Any help?

**Comment by Aranuvir** [comment] 2018-03-17 13:14
This is a bug tracker, not a support forum. For support requests please report to: http://www.makehumancommunity.org/forum/viewforum.php?f=6

BTW, I don't get the point. Perhaps you can get a bit more verbose in the forum, or at least point to one of those YouTube videos.

Closing. Reason: not a bug.

**Closed by Aranuvir** 2018-03-17 13:14 UTC
