### ISSUE TITLE
3D model doesn't display

### ISSUE THREAD

**Issue by TorosFanny** [makehumancommunity/makehuman#65] opened 2019-10-27 06:06 UTC
Version: LONG VERSION: 1.2.0 Alpha4 (UNKNOWN:UNKNOWN)
OS: ArchLinux
Log:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/6369146/67630435-52eb3180-f8c2-11e9-8d7f-cabd221382b3.png">
Issuue:
<img width="843" alt="image" src="https://user-images.githubusercontent.com/6369146/67630437-6dbda600-f8c2-11e9-82ab-07b57470f3f5.png">
However, while the 3D window display nothing, I can get snapshot of 3D human model when I click "Grab screen".

**Comment by Aranuvir** [comment] 2019-10-27 19:20
That looks like a duplicate of #46

**Closed by Aranuvir** 2019-10-27 19:20 UTC
