### ISSUE TITLE
Measure target "Bust circum" not symmetrical for small values

### ISSUE THREAD

**Issue by cfeck** [makehumancommunity/makehuman#61] opened 2019-10-09 19:59 UTC
Steps to reproduce:
- select Modelling/Measure tab
- move "Bust circum" slider all the way to the left

Actual result:
- The mesh is no longer symmetrical around the armpit region

Expected result:
- The figure mesh is still symmetrical

Additional information:
The defect can be seen best with the Baby target (Age slider value 0.0), but happens for all ages and base figures.

**Comment by Aranuvir** [comment] 2019-10-09 21:29
That's more or less a duplicate of #21 and could be considered as a special case of it...

**Comment by black-punkduck** [comment] 2020-05-14 20:08
makehuman/makehuman/data/targets/measure/measure-bust-circ-decr.target
 
only the decreasing element was not working as it should. The helpers deformed even worse. Problem for these fixes is to find the side which looks better. 

The change was created with a script using the numbers of the target file.  We have to change some more targets but this issue will be closed
(Change: 7b72e3f)

**Closed by black-punkduck** 2020-05-14 20:08 UTC

**Comment by SerMesh** [comment] 2020-06-08 13:06
#21 was fixed very quickly and ensured that left and right target sliders were adjusted simultaneously where applicable. But whenever the left and right targets don't match, of if a "central" target in non-symmetric, #21 can't do anything about it. Someone (me) had to go in and symmetrize all the left/right target pairs, as well as "central" targets - but I got distracted by other things. That said, I still mean to contribute fully symmetric targets (and weights) at some point.
